# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

# Event for the workflow
on: push

env:
  NODE_VERSION: '18.x'

# List of jobs
jobs:
  push:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: checkout GitHub Action
        uses: actions/checkout@v3

      - name: setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: 'Resolve Project Dependencies Using PNPM'
        shell: bash
        run: |
          pnpm install

      - name: chromaui
        uses:
          chromaui/action@v1
          # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/docs
          buildScriptName: release
          storybookBuildDir: packages/docs/surprise-docs
          storybookBaseDir: packages/docs
